Repository JugadorXEI/time-travel, pull requests merged in 2024-02, with the labels that each got.

#2 Fix MobjThinker hooks performance
  Lua/1_Gameplay/1_Main/chaseritems.lua
  Lua/2_Cosmetic/Echoes/echoes.lua
Labels: improvement, good first pr

#6 Fix echoqueue leaking
  Lua/2_Cosmetic/Echoes/echoes.lua
Labels: bugfix

#7 Fix Jawz targetting regression
  Lua/1_Gameplay/1_Main/chaseritems.lua
Labels: bugfix

#9 Remove XItemLib, use a base game-oriented fix for item odds
  Lua/0_Main/_general.lua
  Lua/0_Main/dowehavexitemloadedsanityscript.lua
  Lua/0_Main/xItemLib_v112.lua
  Lua/1_Gameplay/1_Main/chaseritems.lua
  Lua/1_Gameplay/1_Main/itemroulette.lua
  Lua/1_Gameplay/1_Main/mainthinker.lua
  Lua/1_Gameplay/1_Main/timetravel.lua
  Lua/1_Gameplay/1_Main/xitemdisabler.lua
  Lua/1_Gameplay/2_Interop/XItem/xitem_eggpanicinterop.lua
  Lua/1_Gameplay/2_Interop/XItem/xitem_juiceboxinterop.lua
  Lua/1_Gameplay/2_Interop/XItem/xitem_kmpinterop.lua
  Lua/1_Gameplay/2_Interop/XItem/xitem_playerarrowinterop.lua
  Lua/1_Gameplay/2_Interop/xiteminterop.lua
Labels: improvement, bugfix
